// Filesystem OKF vault writer. Layout under root:
//
//   projects/{projectId}/research/{slug}--{id}.md
//   projects/{projectId}/documents/{slug}--{id}.md   (knowledge docs w/ project)
//   shared/documents/{slug}--{id}.md                 (knowledge docs, no scope)
//   projects/{projectId}/_index.md                   (generated by the sync)
//   _trash/<same relative path>                      (tombstones)
//
// Writes use the temp-sibling + rename idiom (see fs-blob-store) so a reader
// never observes a half-written file; last-writer-wins is acceptable for a
// derived projection.
//
// The slug comes from a mutable title, so a file's *name* can change while its
// identity does not. Every operation that has to find an existing file
// therefore looks it up by id suffix rather than trusting a recomputed path.

import { mkdir, readdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { matchesId, parseVaultDoc, pathFor, serializeVaultDoc } from './frontmatter.ts';
import {
  CURRENT_OKF_VERSION,
  type VaultDeleteReason,
  type VaultFrontmatter,
  type VaultRef,
  type VaultWriter,
} from './types.ts';

export function createFsVaultWriter(root: string): VaultWriter {
  const baseDir = resolve(root);

  async function writeAtomic(dest: string, content: string): Promise<void> {
    await mkdir(dirname(dest), { recursive: true });
    const tmp = `${dest}.tmp`;
    await writeFile(tmp, content, 'utf8');
    await rename(tmp, dest);
  }

  async function exists(path: string): Promise<boolean> {
    try {
      await stat(path);
      return true;
    } catch {
      return false;
    }
  }

  // Relative paths of every live file carrying this id — normally one, but a
  // crashed rename or a hand-edited vault can leave more.
  async function livePathsFor(ref: VaultRef): Promise<string[]> {
    const dirRel = dirname(pathFor({ kind: ref.kind, id: ref.id, projectId: ref.projectId }));
    let entries: string[];
    try {
      entries = await readdir(join(baseDir, dirRel));
    } catch {
      return [];
    }
    return entries.filter((e) => matchesId(e, ref.id)).map((e) => join(dirRel, e));
  }

  // Move one known-good file into _trash/ at the same relative path, stamping
  // the tombstone fields into whatever frontmatter it already has.
  async function trashFile(relPath: string, at: Date, reason: VaultDeleteReason): Promise<boolean> {
    const livePath = join(baseDir, relPath);
    let raw: string;
    try {
      raw = await readFile(livePath, 'utf8');
    } catch {
      return false;
    }
    const parsed = parseVaultDoc(raw);
    if (parsed === null) return false;
    const doc = serializeVaultDoc(
      { ...parsed.meta, deletedAt: at.toISOString(), deleteReason: reason },
      parsed.body,
    );
    await writeAtomic(join(baseDir, '_trash', relPath), doc);
    await rm(livePath, { force: true });
    return true;
  }

  return {
    async write(meta: VaultFrontmatter, body: string): Promise<void> {
      const relPath = pathFor(meta);
      const dest = join(baseDir, relPath);
      // An in-place overwrite cannot have moved the file, so the sibling sweep
      // below is skipped on the common path — including a steady-state sync,
      // where every write lands on an existing file.
      const overwrite = await exists(dest);
      await writeAtomic(dest, serializeVaultDoc(meta, body));
      if (overwrite) return;

      // The destination is new, so a previous title may have left a file
      // behind. Without this, a title edit would show two files for one node
      // until the next nightly sync — up to 24 hours of a stale duplicate.
      for (const stale of await livePathsFor(meta)) {
        if (stale === relPath) continue;
        await trashFile(stale, new Date(), 'orphaned');
      }
    },

    async tombstone(ref: VaultRef, at: Date, reason: VaultDeleteReason): Promise<void> {
      // The ref usually carries the current title, which makes the expected
      // path a direct hit. It is only a fast path: a title that changed since
      // the last write would miss, and falling through to the scan is what
      // keeps the tombstone carrying the document's body instead of degrading
      // to an empty stub.
      const expected = ref.title !== undefined ? pathFor(ref) : undefined;
      const targets =
        expected !== undefined && (await exists(join(baseDir, expected)))
          ? [expected]
          : await livePathsFor(ref);

      let tombstoned = false;
      for (const relPath of targets) {
        if (await trashFile(relPath, at, reason)) tombstoned = true;
      }
      if (tombstoned) return;

      // Never-written (or unparseable) item: frontmatter-only stub so the
      // tombstone still records what was deleted and when.
      await writeAtomic(
        join(baseDir, '_trash', pathFor(ref)),
        serializeVaultDoc(
          {
            okfVersion: CURRENT_OKF_VERSION,
            id: ref.id,
            kind: ref.kind,
            title: ref.title ?? '(unknown — no vault file existed at deletion)',
            ...(ref.projectId !== undefined && { projectId: ref.projectId }),
            source: 'unknown',
            tags: [],
            createdAt: at.toISOString(),
            updatedAt: at.toISOString(),
            deletedAt: at.toISOString(),
            deleteReason: reason,
          },
          '',
        ),
      );
    },

    async tombstoneFile(relPath: string, at: Date, reason: VaultDeleteReason): Promise<void> {
      await trashFile(relPath, at, reason);
    },

    async writeRaw(relPath: string, content: string): Promise<void> {
      await writeAtomic(join(baseDir, relPath), content);
    },
  };
}
