// Generated `_index.md` — the entry point that makes the vault browsable and
// gives Obsidian's graph view something to draw. Without it the vault is a
// flat set of files with no links between them.
//
// Written by the sync sweep only, never by the request path: building one
// costs a full listing of a project's contents, and two concurrent writes
// would race on it. The cost is staleness — a document created since the last
// sweep is not listed until the next one — which the note says out loud.

import { serializeVaultDoc } from './frontmatter.ts';
import { CURRENT_OKF_VERSION, type VaultIndexFrontmatter, type VaultKind } from './types.ts';

export interface IndexEntry {
  kind: VaultKind;
  id: string;
  title: string;
  /** Vault-root-relative path of the live file, e.g. projects/x/research/y--id.md */
  relPath: string;
}

export interface IndexBucket {
  projectId?: string;
}

export const INDEX_FILENAME = '_index.md';

const NOTE =
  '> Generated by the OKF sync (`pnpm okf:sync`). Anything added since the last\n' +
  '> sweep is not listed yet. The graph is the source of truth; this is derived.';

// Plain codepoint order, not localeCompare: the output has to be
// byte-identical across machines or the sync can never report "no change".
function cmp(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

function byTitleThenId(a: IndexEntry, b: IndexEntry): number {
  return cmp(a.title, b.title) || cmp(a.id, b.id);
}

// Wikilink display text. `[`, `]` and `|` would terminate the link early, and
// a title made only of those collapses to nothing — fall back to the id so
// the entry is still clickable.
function alias(entry: IndexEntry): string {
  const cleaned = entry.title
    .replace(/[[\]|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned === '' ? entry.id : cleaned;
}

// Vault-root-relative target without the extension: the form that resolves
// under all three of Obsidian's link-format settings.
function link(entry: IndexEntry): string {
  return `- [[${entry.relPath.replace(/\.md$/, '')}|${alias(entry)}]]`;
}

export function renderVaultIndex(bucket: IndexBucket, entries: IndexEntry[]): string {
  const research = entries.filter((e) => e.kind === 'research').sort(byTitleThenId);
  const documents = entries.filter((e) => e.kind === 'knowledge_document').sort(byTitleThenId);

  const meta: VaultIndexFrontmatter = {
    okfVersion: CURRENT_OKF_VERSION,
    kind: 'index',
    generated: true,
    ...(bucket.projectId !== undefined && { projectId: bucket.projectId }),
    counts: { research: research.length, documents: documents.length },
  };

  const lines: string[] = [`# ${bucket.projectId ?? 'Shared'}`, '', NOTE];
  for (const [label, list] of [
    ['Research', research],
    ['Documents', documents],
  ] as const) {
    if (list.length === 0) continue;
    lines.push('', `## ${label}`, '', ...list.map(link));
  }
  return serializeVaultDoc(meta, lines.join('\n'));
}
